Ex_09_Project/Areas/Angular/Controllers/SPAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ex_09_Project.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace Ex_09_Project.Areas.Angular.Controllers
{
    [Area("Angular")]
    public class SPAController : Controller
    {
        IEmployeeRepository repo;
        public SPAController (IEmployeeRepository repo) { this.repo = repo; }
        public IActionResult Index()
        {
            return View();
        }
        public JsonResult ProductList()
        {
            var data = repo.GetEmployees().Select(x => new {
                x.EmployeeId, x.EmployeeName, x.JoinDate, Grade=x.Grade.ToString(), x.DepartmentId, DepartmentName=x.Department.DepartmentName
            }).ToList();
            return Json(data);
        }
    }
}

Ex_09_Project/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Ex_09_Project.Models;
using Ex_09_Project.Repositories;
using Ex_09_Project.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Ex_09_Project.Controllers
{
    //[Authorize]
    public class DepartmentsController : Controller
    {
        IEmployeeRepository repo;
        public DepartmentsController(IEmployeeRepository repo) { this.repo = repo; }
        public IActionResult Index(int pg =1)
        {
            var data = repo.GetDepartments().OrderBy(x => x.DepartmentId);
            ViewBag.Pager = new PagerModel
            {
                TotalPages = (int)Math.Ceiling((double)data.Count() / 5),
                CurrentPage = pg
            };
            return View(data.Skip((pg-1)*5).Take(5).ToList());
        }
        public IActionResult Summary(int pg=1, string sort="", string search="")
        {
            Thread.Sleep(2000);
            var data = repo.GetSummary();
            ViewBag.Pager = new PagerModel
            {
                TotalPages=(int)Math.Ceiling((double)data.Count()/5),
                CurrentPage=pg
            };
            if (sort == "") { ViewBag.NameSort = "name"; }
            ViewBag.NameSort = sort == "name" ? "name_desc" : "name";
            ViewBag.CountSort = sort == "count" ? "count_desc" : "count";

            ViewBag.CurrentSort = sort == "" ? "name" : sort;
            ViewBag.Search = search;
            switch (sort)
            {
                case "name":
                    data = data.OrderBy(x => x.DepartmentName);
                    break;
                case "name_desc":
                    data = data.OrderByDescending(x => x.DepartmentName);
                    break;
                case "count":
                    data = data.OrderBy(x => x.EmployeeCount);
                    break;
                case "count_desc":
                    data = data.OrderByDescending(x => x.EmployeeCount);
                    break;
                default:
                    data = data.OrderBy(x => x.DepartmentId);
                    break;
            }
            if (!string.IsNullOrEmpty(search))
            {
                data = data.Where(x => x.DepartmentName.ToLower().StartsWith(search.ToLower()));
            }
            var modelData = data.Skip((pg - 1) * 5).Take(5).ToList();
            ///////////////////////////////////////////////////////////////////////
            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("_DepartmentSummary", modelData);
            }
            ///////////////////////////////////////////////////////////////////////
            return View(modelData);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Department dept)
        {
            if (ModelState.IsValid) {
                repo.InsertDepartment(dept);
                return RedirectToAction("Index");
            }
            return View(dept);
        }
        public IActionResult Edit(int id)
        {
            var dept = repo.GetDepartmentById(id);
            if(dept == null)
            {
                return NotFound();
            }
            return View(dept);
        }
        [HttpPost]
        public IActionResult Edit(Department dept)
        {
            if (ModelState.IsValid)
            {
                repo.EditDepartment(dept);
                return RedirectToAction("Index");
            }
            return View(dept);
        }
        public IActionResult Delete(int id)
        {
            var dept = repo.GetDepartmentById(id);
            if (dept == null)
            {
                return NotFound();
            }
            return View(dept);
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult ApplyDelete(int id)
        {
            
            repo.DeleteDepartment(id);
            return RedirectToAction("Index");
           
            
        }
    }
}

Ex_09_Project/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ex_09_Project.Models;
using Ex_09_Project.Repositories;

namespace Ex_09_Project.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IEmployeeRepository repo;

        public EmployeesController(IEmployeeRepository repo)
        {
            this.repo  = repo;
        }
        // GET: Employees
        public IActionResult Index()
        {
            
            return View(this.repo.GetEmployees().ToList());
        }

        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(repo.GetDepartments(), "DepartmentId", "DepartmentName");
            ViewData["GradeList"] = new SelectList(repo.GradeList());
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("EmployeeId,EmployeeName,JoinDate,Grade,DepartmentId")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                repo.InsertEmployee(employee);
               
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(repo.GetDepartments(), "DepartmentId", "DepartmentName", employee.DepartmentId);
            ViewData["GradeList"] = new SelectList(repo.GradeList());
            return View(employee);
        }

        // GET: Employees/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee =  repo.GetEmployeeById(id.Value);
            if (employee == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(repo.GetDepartments(), "DepartmentId", "DepartmentName", employee.DepartmentId);
            ViewData["GradeList"] = new SelectList(repo.GradeList());
            return View(employee);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("EmployeeId,EmployeeName,JoinDate,Grade,DepartmentId")] Employee employee)
        {
            if (id != employee.EmployeeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
               
                 repo.EditEmployee(employee);
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(repo.GetDepartments(), "DepartmentId", "DepartmentName", employee.DepartmentId);
            ViewData["GradeList"] = new SelectList(repo.GradeList());
            return View(employee);
        }

       
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = repo.GetEmployeeById(id.Value);
                
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            repo.DeleteEmployee(id);
            return RedirectToAction(nameof(Index));
        }

        //private bool EmployeeExists(int id)
        //{
        //    return _context.Employees.Any(e => e.EmployeeId == id);
        //}
    }
}

Ex_09_Project/Views/Shared/_DepartmentSummary.cshtml
@model IEnumerable<Ex_09_Project.ViewModels.DepartmentVM>




<table class="table table-bordered">
    <thead class="thead-light">
        <tr style="background-color:aliceblue">
            
            <th>
               
               
                <a  data-ajax="true"
                   data-ajax-loading="#loading"
                   data-ajax-mode="replace"
                   data-ajax-update="#holder"
                   href='@Url.Action("Summary", "Departments", new { sort=ViewBag.NameSort, search=ViewBag.Search})'>
                    @Html.DisplayNameFor(model => model.DepartmentName)
                    <i class="fa @(ViewBag.NameSort == "name"? "fa-chevron-down": "fa-chevron-up")"></i>
                </a>

                
                   
                    
              
            
            </th>
            <th>
                <a data-ajax="true"
                   data-ajax-loading="#loading"
                   data-ajax-mode="replace"
                   data-ajax-update="#holder"
                   href='@Url.Action("Summary", "Departments", new { sort=ViewBag.CountSort, search=ViewBag.Search})'>
                    @Html.DisplayNameFor(model => model.EmployeeCount)
                    <i class="fa @(ViewBag.CountSort == "count"? "fa-chevron-down": "fa-chevron-up")"></i>
                </a>
            </th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
               
                <td>
                    @Html.DisplayFor(modelItem => item.DepartmentName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmployeeCount)
                </td>
                
            </tr>
        }
    </tbody>
</table>
<div class="d-flex flex-row-reverse">
    <ul class="pagination pagination-sm">
        @if (ViewBag.Pager.CurrentPage > 1)
        {
            <li class="page-item">
                <a class="page-link" data-ajax="true"
                    data-ajax-loading="#loading"
                   data-ajax-mode="replace"
                   data-ajax-update="#holder"
                   href='@Url.Action("Summary", "Departments", new { pg = ViewBag.Pager.CurrentPage-1, sort=ViewBag.CurrentSort, search=ViewBag.Search})'>
                    <i class="fa fa-long-arrow-left"></i>
                </a>
            </li>
        }
        @for (int i = 1; i <= ViewBag.Pager.TotalPages; i++)
        {
            if (i == ViewBag.Pager.CurrentPage)
            {
                <li class="page-item active"><span class="page-link">@i</span></li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" data-ajax="true"
                       data-ajax-loading="#loading"
                       data-ajax-mode="replace"
                       data-ajax-update="#holder"
                       href='@Url.Action("Summary", "Departments", new { pg = i, sort=ViewBag.CurrentSort, search=ViewBag.Search})'>@i</a>

                </li>
            }

        }
        @if (ViewBag.Pager.CurrentPage < ViewBag.Pager.TotalPages)
        {
            <li class="page-item">
                <a class="page-link" data-ajax="true"
                   data-ajax-loading="#loading"
                   data-ajax-mode="replace"
                   data-ajax-update="#holder"
                   href='@Url.Action("Summary", "Departments", new { pg = ViewBag.Pager.CurrentPage+1, sort=ViewBag.CurrentSort, search=ViewBag.Search})'>
                    <i class="fa fa-long-arrow-right"></i>
                </a>
            </li>
        }
    </ul>
</div>

Ex_09_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ex_09_Project</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ex_09_Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Summary">Summary View</a>
                        </li>
                      
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Manage
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Departments" asp-action="Index">Department</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Angular" asp-controller="SPA" asp-action="Index">Angular SPA</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Ex_09_by helal - <a asp-area="" asp-controller="Home" asp-action="Index">Back to Home page</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>